services:
  backend:
    build: .
    container_name: ggbot-backend
    env_file: .env
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    # Si tu veux voir les logs propres dans Docker Desktop
    tty: true

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 30
    container_name: ggbot-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
