[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:redis]
command=/usr/bin/redis-server --save "" --appendonly no --bind 127.0.0.1
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:nest]
directory=/opt/ggbot-backend
command=/usr/bin/node dist/main.js
environment=PORT=%(ENV_NEST_PORT)s,REDIS_URL=%(ENV_NEST_REDIS_URL)s,LOGS_PORT=%(ENV_NEST_LOGS_PORT)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=20

[program:agent]
command=/usr/local/bin/ggbot-agent -cfg /etc/ggbot/config.yaml -cmd agent
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=30
